export const GAME_CONSTANTS = {
    STARTING_COINS: 10,
    BIDDING_TIMER_DURATION: 10, // seconds
    COINS_AWARDED_PER_ROUND: 2,
    LOW_COIN_THRESHOLD: 5,
    QUESTION_DISPLAY_DELAY: 4000, // 4 seconds
    TRUTH_GUESS_DELAY: 5000, // 5 seconds
    BID_TIED_RESTART_DELAY: 3000, // 3 seconds
} as const; 